settings:
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: test
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: rs-api
    # 端口号
    port: 8000 # 服务端口号
    readtimeout: 1
    writertimeout: 2
    # 数据权限功能开关
    enabledp: true
  logger:
    # 日志存放路径
    path: access/logs
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: '' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 操作数据库的记录开关
    enableddb: true
  jwt:
    # token 密钥，生产环境时及的修改
    secret: rs-api
    # token 过期时间 单位：秒
    #默认过期时间 5个小时
    timeout: 180000
  database:
    driver: mysql
#    source: xarscloud:xarscloud;123@tcp(60.205.112.51:13306)/rs_devops?charset=utf8&parseTime=True&loc=Local&timeout=8000ms
    source: xarscloud:xarscloud;123@tcp(60.205.112.51:13306)/rs_store?charset=utf8&parseTime=True&loc=Local&timeout=8000ms

  gen:
    # 代码生成读取的数据库名称
    dbname: rs_store
    # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
    frontpath: ../go-admin-ui/src
  extend: # 扩展项使用说明
    prometheus:
      endpoint:  "http://8.140.194.41:8090"
      username: "admin"
      password: "iFAu1InvVpLj"
    frps:
      address: "root@frp.xarscloud.com"
      id_rsa: "/root/.ssh/id_rsa"
    automation:
      hostname: "http://8.140.194.41:8001/data/storage/init-shell/update_hostname.sh"
  queue:
    memory:
      poolSize: 100
  locker:
    redis: